package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/devteam/backend/internal/models"
	"github.com/devteam/backend/pkg/gitprovider"
)

// PullRequestPublisher вызывается оркестратором после того, как задача
// дошла до status=completed: открывает Pull Request с веткой задачи в base
// проекта. Реализация может быть nil (тогда оркестратор просто пропустит шаг).
type PullRequestPublisher interface {
	Publish(ctx context.Context, task *models.Task, project *models.Project) (*gitprovider.PullRequest, error)
}

// gitPRPublisher — продакшен-реализация: использует gitprovider.Factory + Encryptor
// для расшифровки токена из project.GitCredential, и зовёт provider.CreatePullRequest.
//
// Не падает фатально, если у проекта нет credentials или provider не поддерживает PR
// (например, local) — в этом случае Publish возвращает ErrPullRequestSkipped, и оркестратор
// логирует skip вместо ошибки.
type gitPRPublisher struct {
	factory   gitprovider.Factory
	encryptor Encryptor
	log       *slog.Logger
}

// NewGitPRPublisher создаёт PR-publisher. Любой из аргументов может быть nil — тогда
// Publish ничего не делает (удобно для тестов и dev-режима без AES-ключа).
func NewGitPRPublisher(factory gitprovider.Factory, encryptor Encryptor, log *slog.Logger) PullRequestPublisher {
	if log == nil {
		log = slog.Default()
	}
	return &gitPRPublisher{factory: factory, encryptor: encryptor, log: log}
}

// ErrPullRequestSkipped — publisher распознал, что PR создавать не нужно/нечем
// (нет credentials, провайдер local, ветка пуста). Не фатально для pipeline.
var ErrPullRequestSkipped = errors.New("pull request: skipped")

func (p *gitPRPublisher) Publish(ctx context.Context, task *models.Task, project *models.Project) (*gitprovider.PullRequest, error) {
	if p == nil || p.factory == nil {
		return nil, ErrPullRequestSkipped
	}
	if task == nil || project == nil {
		return nil, ErrPullRequestSkipped
	}
	if task.BranchName == nil || *task.BranchName == "" {
		return nil, fmt.Errorf("%w: empty branch", ErrPullRequestSkipped)
	}
	if project.GitURL == "" || string(project.GitProvider) == "local" {
		return nil, fmt.Errorf("%w: non-PR provider (%s)", ErrPullRequestSkipped, project.GitProvider)
	}
	if project.GitCredential == nil {
		return nil, fmt.Errorf("%w: no git_credential on project", ErrPullRequestSkipped)
	}

	creds := gitprovider.Credentials{}
	decrypted, err := p.encryptor.Decrypt(project.GitCredential.EncryptedValue, []byte(project.GitCredential.ID.String()))
	if err != nil {
		return nil, fmt.Errorf("decrypt git credential: %w", err)
	}
	switch project.GitCredential.AuthType {
	case models.GitCredentialAuthToken, models.GitCredentialAuthOAuth:
		creds.Token = string(decrypted)
	case models.GitCredentialAuthSSHKey:
		creds.SSHKey = string(decrypted)
	}

	provider, err := p.factory.Create(string(project.GitProvider), creds)
	if err != nil {
		return nil, fmt.Errorf("git factory: %w", err)
	}

	base := project.GitDefaultBranch
	if base == "" {
		base = "main"
	}
	body := fmt.Sprintf("Auto-generated by DevTeam pipeline.\n\nTask: %s\n\n%s", task.Title, task.Description)
	pr, err := provider.CreatePullRequest(ctx, project.GitURL, gitprovider.PRCreateOptions{
		Title:      fmt.Sprintf("DevTeam: %s", task.Title),
		Body:       body,
		HeadBranch: *task.BranchName,
		BaseBranch: base,
		Labels:     []string{"devteam", "auto-generated"},
	})
	if err != nil {
		return nil, fmt.Errorf("create PR: %w", err)
	}
	p.log.Info("PR opened", "project_id", project.ID, "task_id", task.ID, "branch", *task.BranchName, "pr_number", pr.Number, "pr_url", pr.HTMLURL)
	return pr, nil
}
